# listen on all interfaces
network:
  bind_host: 0.0.0.0

# default ports (http 9200, tcp 9300)
http:
  port: 9200

transport:
  tcp:
    port: 9300

# data and logs locations
# FIXME: figure out best placement for logs
path:
  data: /data
  logs: /data/elasticsearch

# TODO: cluster configuration (cluster and node name + discovery)
